- name: variables
  hosts: local
  connection: local
  # vars: # play level variables
  #   GREET: "PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars: 
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from  {{ GREET }}"

  #1 command line args 
  #2 task
  #3 files
  #4 prompt
  #5 play
  #6 inventory
  #7 roles
  