- name: Devops course information
  hosts: local
  connection: local
  vars: 
    course: "Devops with AWS" # string
    duration: 120 #number
    topics: # List
    - linux
    - shell
    - ansible
    - AWS
    live: true #boolean
    tools: # map
      ci: jenkins
      cloud: AWS
      containerization: docker
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ couse_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it {{ live }}, tools covered are: {{ tools}}"